# Generated by Django 4.1.5 on 2023-01-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(default="Joao", max_length=150),
            preserve_default=False,
        ),
    ]
