# Generated by Django 4.1.5 on 2023-01-09 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_number",
                    models.IntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MaxValueValidator(99),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "Available"), ("occupied", "Occupied")],
                        default="available",
                        max_length=9,
                    ),
                ),
                (
                    "musics_count",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(2),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
