# Generated by Django 4.1.5 on 2023-01-06 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Menu",
            new_name="Table",
        ),
    ]
