# Generated by Django 4.1.5 on 2023-01-06 19:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tables", "0002_rename_menu_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="user",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="table",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="table",
            name="musics_count",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(2),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
