# Generated by Django 4.1.5 on 2023-01-10 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="table_number",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(99),
                    django.core.validators.MinValueValidator(1),
                ]
            ),
        ),
    ]
