# Generated by Django 4.1.5 on 2023-01-06 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tables", "0003_table_user_alter_table_musics_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="table",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
