# Generated by Django 4.0.7 on 2023-01-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('drinks', 'Drinks'), ('foods', 'Foods'), ('disserts', 'Disserts')], max_length=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
