# Generated by Django 4.1.5 on 2023-01-10 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="table_orders",
                to="tables.table",
            ),
        ),
    ]
